name: Create System Files For GitHub Release


env:
    project_url: "https://github.com/${{github.repository}}"
    latest_manifest_url: "https://github.com/${{github.repository}}/releases/latest/download/system.json"
    release_system_url: "https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/system.zip"


on:
    release:
        types: [published]


jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v3

            -   name: Build assets [1/2] - yarn install
                run: yarn install

            -   name: Build assets [2/2] - yarn build
                run: NODE_ENV=production yarn run build

            -   name: Pack compendiums
                run: yarn run pack-packs

            -   name: Extract Version From Tag
                id: get_version
                uses: battila7/get-version-action@v2

            -   name: Modify System Manifest With Release-Specific Values
                id: sub_manifest_link_version
                uses: cschleiden/replace-tokens@v1
                with:
                    files: 'system.json'
                env:
                    VERSION: ${{steps.get_version.outputs.version-without-v}}
                    URL: ${{ env.project_url }}
                    MANIFEST: ${{ env.latest_manifest_url }}
                    DOWNLOAD: ${{ env.release_system_url }}

            -   name: Create System Archive
                run: |
                    zip                                    \
                      --recurse-paths                      \
                       ./system.zip                        \
                      system.json                          \
                      template.json                        \
                      README.md                            \
                      CHANGELOG.md                         \
                      LICENSE                              \
                      templates                            \
                      assets/                              \
                      packs/                               \
                      lang/

            -   name: Update Release With Files
                id: create_version_release
                uses: ncipollo/release-action@v1
                with:
                    allowUpdates: true
                    name: ${{ github.event.release.name }}
                    draft: ${{ github.event.release.unpublished }}
                    prerelease: ${{ github.event.release.prerelease }}
                    token: ${{ secrets.GITHUB_TOKEN }}
                    artifacts: './system.json, ./system.zip'
                    tag: ${{ github.event.release.tag_name }}
                    body: ${{ github.event.release.body }}
